name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.18.0
  firebase_auth: ^4.12.1
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.15.1
  image_picker: ^1.0.4
  provider: ^6.0.5
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\images\xolidayboy.jpg
    - assets\images\Кракен.jpg
    - assets\images\вСписках.jpg